import { MODULE_TYPES, type ModuleType, type NavigationItem, type ModuleConfig } from '@/lib/types';

// 🧭 Sistema de Navegación Unificado

// Configuración de módulos del sistema
export const MODULES_CONFIG: Record<ModuleType, ModuleConfig> = {
  dashboard: {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Panel principal con estadísticas',
    icon: '📊',
    color: 'bg-blue-500',
    href: '/dashboard',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: true,
  },
  patients: {
    id: 'patients',
    title: 'Pacientes',
    description: 'Gestión de pacientes',
    icon: '👥',
    color: 'bg-green-500',
    href: '/patients',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: true,
  },
  triage: {
    id: 'triage',
    title: 'Triage',
    description: 'Sistema de priorización',
    icon: '🏥',
    color: 'bg-red-500',
    href: '/triage',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero'],
    isActive: true,
  },
  historias: {
    id: 'historias',
    title: 'Historias Clínicas',
    description: 'Gestión de historias médicas',
    icon: '📋',
    color: 'bg-purple-500',
    href: '/historias',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero'],
    isActive: true,
  },
  farmacia: {
    id: 'farmacia',
    title: 'Farmacia',
    description: 'Gestión de medicamentos',
    icon: '💊',
    color: 'bg-yellow-500',
    href: '/farmacia',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  citas: {
    id: 'citas',
    title: 'Citas',
    description: 'Programación de citas',
    icon: '🗓️',
    color: 'bg-indigo-500',
    href: '/citas',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  laboratorio: {
    id: 'laboratorio',
    title: 'Laboratorio',
    description: 'Exámenes y resultados',
    icon: '🧪',
    color: 'bg-cyan-500',
    href: '/laboratorio',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero'],
    isActive: false, // Pendiente de implementación
  },
  admision: {
    id: 'admision',
    title: 'Admisión',
    description: 'Proceso de admisión',
    icon: '🏥',
    color: 'bg-orange-500',
    href: '/admision',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  facturacion: {
    id: 'facturacion',
    title: 'Facturación',
    description: 'Gestión financiera',
    icon: '💰',
    color: 'bg-emerald-500',
    href: '/facturacion',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  reportes: {
    id: 'reportes',
    title: 'Reportes',
    description: 'Generación de reportes',
    icon: '📊',
    color: 'bg-slate-500',
    href: '/reportes',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  admin: {
    id: 'admin',
    title: 'Administración',
    description: 'Configuración del sistema',
    icon: '⚙️',
    color: 'bg-gray-500',
    href: '/admin',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: true,
  },
  configuracion: {
    id: 'configuracion',
    title: 'Configuración',
    description: 'Configuraciones avanzadas',
    icon: '🔧',
    color: 'bg-gray-600',
    href: '/configuracion',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  // Nuevos módulos
  asistencial: {
    id: 'asistencial',
    title: 'Asistencial',
    description: 'Gestión asistencial y atención médica',
    icon: '🏨',
    color: 'bg-teal-500',
    href: '/asistencial',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  inventario: {
    id: 'inventario',
    title: 'Inventario',
    description: 'Control de inventario y suministros',
    icon: '📦',
    color: 'bg-amber-500',
    href: '/inventario',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  auditoria: {
    id: 'auditoria',
    title: 'Auditoría',
    description: 'Auditoría y control de calidad',
    icon: '🔍',
    color: 'bg-violet-500',
    href: '/auditoria',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'imagenes-diagnosticas': {
    id: 'imagenes-diagnosticas',
    title: 'Imágenes Diagnósticas',
    description: 'Gestión de imágenes médicas',
    icon: '🖼️',
    color: 'bg-pink-500',
    href: '/imagenes-diagnosticas',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero'],
    isActive: false, // Pendiente de implementación
  },
  calidad: {
    id: 'calidad',
    title: 'Calidad',
    description: 'Gestión de calidad y acreditación',
    icon: '⭐',
    color: 'bg-rose-500',
    href: '/calidad',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  contabilidad: {
    id: 'contabilidad',
    title: 'Contabilidad',
    description: 'Gestión contable y financiera',
    icon: '📈',
    color: 'bg-lime-500',
    href: '/contabilidad',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  presupuesto: {
    id: 'presupuesto',
    title: 'Presupuesto',
    description: 'Gestión presupuestaria',
    icon: '📋',
    color: 'bg-sky-500',
    href: '/presupuesto',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  nomina: {
    id: 'nomina',
    title: 'Nómina',
    description: 'Gestión de recursos humanos',
    icon: '👥',
    color: 'bg-fuchsia-500',
    href: '/nomina',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  cartera: {
    id: 'cartera',
    title: 'Cartera',
    description: 'Gestión de cartera y cobranza',
    icon: '💳',
    color: 'bg-cyan-500',
    href: '/cartera',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  // Módulos adicionales
  'recibos-caja': {
    id: 'recibos-caja',
    title: 'Recibos de Caja',
    description: 'Gestión de recibos de caja',
    icon: '🧾',
    color: 'bg-green-600',
    href: '/recibos-caja',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  traslados: {
    id: 'traslados',
    title: 'Traslados',
    description: 'Gestión de traslados de pacientes',
    icon: '🚑',
    color: 'bg-orange-600',
    href: '/traslados',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'homologaciones-proc': {
    id: 'homologaciones-proc',
    title: 'Homologaciones Proc',
    description: 'Gestión de homologaciones de procedimientos',
    icon: '🔬',
    color: 'bg-purple-600',
    href: '/homologaciones-proc',
    requiresAuth: true,
    roles: ['Médico', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'anexo-tecnico-inconsistencia': {
    id: 'anexo-tecnico-inconsistencia',
    title: 'Anexo Técnico - Inconsistencia BD',
    description: 'Gestión de inconsistencias en base de datos',
    icon: '⚠️',
    color: 'bg-red-600',
    href: '/anexo-tecnico-inconsistencia',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'anexo-tecnico-informe-urgencia': {
    id: 'anexo-tecnico-informe-urgencia',
    title: 'Anexo Técnico - Informe Urgencia',
    description: 'Informes de atención de urgencias',
    icon: '🚨',
    color: 'bg-red-700',
    href: '/anexo-tecnico-informe-urgencia',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'anexo-tecnico-autorizaciones': {
    id: 'anexo-tecnico-autorizaciones',
    title: 'Anexo Técnico - Autorizaciones',
    description: 'Gestión de autorizaciones médicas',
    icon: '✅',
    color: 'bg-blue-600',
    href: '/anexo-tecnico-autorizaciones',
    requiresAuth: true,
    roles: ['Médico', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'resolucion-202': {
    id: 'resolucion-202',
    title: 'Resolución 202',
    description: 'Gestión de Resolución 202',
    icon: '📋',
    color: 'bg-indigo-600',
    href: '/resolucion-202',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'grupos-etareos': {
    id: 'grupos-etareos',
    title: 'Grupos Etáreos',
    description: 'Gestión de grupos etáreos',
    icon: '👥',
    color: 'bg-teal-600',
    href: '/grupos-etareos',
    requiresAuth: true,
    roles: ['Médico', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  furips: {
    id: 'furips',
    title: 'FURIPS',
    description: 'Gestión de FURIPS',
    icon: '📊',
    color: 'bg-amber-600',
    href: '/furips',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  furtran: {
    id: 'furtran',
    title: 'FURTRAN',
    description: 'Gestión de FURTRAN',
    icon: '📈',
    color: 'bg-lime-600',
    href: '/furtran',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  'anexo-tecnico-uno': {
    id: 'anexo-tecnico-uno',
    title: 'Anexo Técnico Uno',
    description: 'Anexo técnico principal',
    icon: '📄',
    color: 'bg-sky-600',
    href: '/anexo-tecnico-uno',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
  informe: {
    id: 'informe',
    title: 'Informe',
    description: 'Generación y gestión de informes',
    icon: '📋',
    color: 'bg-fuchsia-600',
    href: '/informe',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
    isActive: false, // Pendiente de implementación
  },
  proceso: {
    id: 'proceso',
    title: 'Proceso',
    description: 'Gestión de procesos del sistema',
    icon: '⚙️',
    color: 'bg-gray-600',
    href: '/proceso',
    requiresAuth: true,
    roles: ['Administrador'],
    isActive: false, // Pendiente de implementación
  },
};

// Navegación principal
export const MAIN_NAVIGATION: NavigationItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    href: '/dashboard',
    icon: '📊',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
  },
  {
    id: 'patients',
    title: 'Pacientes',
    href: '/patients',
    icon: '👥',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
  },
  {
    id: 'triage',
    title: 'Triage',
    href: '/triage',
    icon: '🏥',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero'],
  },
  {
    id: 'historias',
    title: 'Historias Clínicas',
    href: '/historias',
    icon: '📋',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero'],
  },
  {
    id: 'asistencial',
    title: 'Asistencial',
    href: '/asistencial',
    icon: '🏨',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
  },
  {
    id: 'inventario',
    title: 'Inventario',
    href: '/inventario',
    icon: '📦',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'auditoria',
    title: 'Auditoría',
    href: '/auditoria',
    icon: '🔍',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'imagenes-diagnosticas',
    title: 'Imágenes Diagnósticas',
    href: '/imagenes-diagnosticas',
    icon: '🖼️',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero'],
  },
  {
    id: 'calidad',
    title: 'Calidad',
    href: '/calidad',
    icon: '⭐',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'contabilidad',
    title: 'Contabilidad',
    href: '/contabilidad',
    icon: '📈',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'presupuesto',
    title: 'Presupuesto',
    href: '/presupuesto',
    icon: '📋',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'nomina',
    title: 'Nómina',
    href: '/nomina',
    icon: '👥',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'cartera',
    title: 'Cartera',
    href: '/cartera',
    icon: '💳',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'admin',
    title: 'Administración',
    href: '/admin',
    icon: '⚙️',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  // Módulos adicionales
  {
    id: 'recibos-caja',
    title: 'Recibos de Caja',
    href: '/recibos-caja',
    icon: '🧾',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'traslados',
    title: 'Traslados',
    href: '/traslados',
    icon: '🚑',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
  },
  {
    id: 'homologaciones-proc',
    title: 'Homologaciones Proc',
    href: '/homologaciones-proc',
    icon: '🔬',
    requiresAuth: true,
    roles: ['Médico', 'Administrador'],
  },
  {
    id: 'anexo-tecnico-inconsistencia',
    title: 'Anexo Técnico - Inconsistencia BD',
    href: '/anexo-tecnico-inconsistencia',
    icon: '⚠️',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'anexo-tecnico-informe-urgencia',
    title: 'Anexo Técnico - Informe Urgencia',
    href: '/anexo-tecnico-informe-urgencia',
    icon: '🚨',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
  },
  {
    id: 'anexo-tecnico-autorizaciones',
    title: 'Anexo Técnico - Autorizaciones',
    href: '/anexo-tecnico-autorizaciones',
    icon: '✅',
    requiresAuth: true,
    roles: ['Médico', 'Administrador'],
  },
  {
    id: 'resolucion-202',
    title: 'Resolución 202',
    href: '/resolucion-202',
    icon: '📋',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'grupos-etareos',
    title: 'Grupos Etáreos',
    href: '/grupos-etareos',
    icon: '👥',
    requiresAuth: true,
    roles: ['Médico', 'Administrador'],
  },
  {
    id: 'furips',
    title: 'FURIPS',
    href: '/furips',
    icon: '📊',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'furtran',
    title: 'FURTRAN',
    href: '/furtran',
    icon: '📈',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'anexo-tecnico-uno',
    title: 'Anexo Técnico Uno',
    href: '/anexo-tecnico-uno',
    icon: '📄',
    requiresAuth: true,
    roles: ['Administrador'],
  },
  {
    id: 'informe',
    title: 'Informe',
    href: '/informe',
    icon: '📋',
    requiresAuth: true,
    roles: ['Médico', 'Enfermero', 'Administrador'],
  },
  {
    id: 'proceso',
    title: 'Proceso',
    href: '/proceso',
    icon: '⚙️',
    requiresAuth: true,
    roles: ['Administrador'],
  },
];

// Utilidades de navegación
export const getModulesByRole = (userRole: string): ModuleConfig[] => {
  return Object.values(MODULES_CONFIG).filter(
    (module) => module.roles.includes(userRole) && module.isActive
  );
};

export const getNavigationByRole = (userRole: string): NavigationItem[] => {
  return MAIN_NAVIGATION.filter(
    (item) => item.roles?.includes(userRole)
  );
};

export const isModuleAccessible = (moduleId: ModuleType, userRole: string): boolean => {
  const module = MODULES_CONFIG[moduleId];
  return module.isActive && module.roles.includes(userRole);
}; 